---

- name: Install postgres packages
  ansible.builtin.yum:
    name: postgresql-server
    state: latest

- name: Check if PostgreSQL database is initialized.
  ansible.builtin.stat:
    path: "{{ pg_data }}"
  register: pgdata_dir_version

- name: Perform PostgreSQL database initialization if required.
  ansible.builtin.command: postgresql-setup initdb
  when: not pgdata_dir_version.stat.exists
  notify:
    - Restart_postgresql

- name: Start PostgreSQL service and enable PostgreSQL to start at boot time
  ansible.builtin.service:
    name: postgresql.service
    enabled: true
  notify:
    - Restart_postgresql
