---
# tasks file for app-tier
- name: Install tomcat packages
  ansible.builtin.yum:
    name: tomcat
    state: latest

- name: Create tomcat ROOT directory
  ansible.builtin.file:
    path: "{{ webapps }}/ROOT"
    state: directory

- name: Copy index.html to tomcat webapps ROOT"
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ webapps }}/ROOT/index.html"
    mode: 0644
  notify:
    - Restart_tomcat

- name: Start Tomcat service and enable Tomcat to start at boot time
  ansible.builtin.service:
    name: tomcat.service
    enabled: true
  notify:
    - Restart_tomcat
